name: 'More Flexible Doxygen GitHub Pages Deploy Action'
author: 'Haowen Yao, Jonah Lawrence'
description: 'Make docs with Doxygen then deploy the generated HTML to GitHub pages. Extended for more flexibility'
branding:
  icon: "upload-cloud"
  color: "blue"

inputs:
  github_token:
    description: 'A GitHub token for pushing to the repo. Example: https://git.io/passing-token'
    required: true
  running_folder:
    description: 'Folder where the Doxygen command will be run (in relative to the root of the repository)'
    required: true
    default: "docs"
  html_folder:
    description: 'Folder where Doxygen will generate the HTML build files (in relative to the root of the repository)'
    required: true
    default: "docs/html"
  config_file:
    description: 'Name of the Doxygen configuration file'
    required: true
    default: "Doxyfile"
  target_repo:
    description: 'The repository to push the generated files to'
    required: false
  target_folder:
    description: 'Directory on the deployment branch for pushing the build files'
    required: false
  target_branch:
    description: 'Branch name for pushing GitHub pages files'
    required: true
    default: "main"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: "true"

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y wget graphviz doxygen
      shell: bash

    - name: Change directory to running folder
      run: cd ${{ inputs.running_folder }}
      shell: bash

    - name: Generate Doxygen Documentation
      run: doxygen ${{ inputs.config_file }}
      shell: bash

    - name: Change directory back to previous state
      run: cd -
      shell: bash

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ inputs.github_token }}
        branch: ${{ inputs.target_branch }}
        folder: ${{ inputs.html_folder }}
        target-folder: ${{ inputs.target_folder }}
        repository-name: ${{ inputs.target_repo }}
